"""
Playbook Seeder — creates the 10 canonical starting playbooks.
Safe to run multiple times (skips existing by name).
"""
from __future__ import annotations
from datetime import datetime
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.playbook import Playbook

_INITIAL_PLAYBOOKS = [
    {
        "name": "Budget Gamer",
        "emoji": "🎮",
        "status": "active",
        "target_use_case": "gaming",
        "target_customer": "Kids / Teens",
        "what_they_use_it_for": "Fortnite, Minecraft, Roblox, Valorant, Discord, streaming",
        "what_they_want_from_build": "Something that runs games at 1080p. Budget matters more than specs.",
        "critical_success_factors": ["Price under £350", "Runs AAA titles at 1080p", "GPU present", "Reliable brand"],
        "profit_opportunity_score": 5.0,
        "market_size_score": 8.0,
        "resellability_score": 8.0,
        "liquidity_score": 9.0,
        "risk_score": 3.0,
        "market_growth_direction": "Stable",
        "requirements": {"cpu_min_tier": "i5", "ram_min_gb": 16, "gpu_required": True, "psu_required": True},
        "search_strategy": {
            "keywords": ["gaming pc no gpu", "gaming pc rtx 3060", "gaming pc gtx 1660", "budget gaming desktop"],
            "price_min": 80, "price_max": 250, "listing_types": ["buy_it_now", "auction"]
        },
        "profit_strategy": {"target_profit_gbp": 100, "target_margin_pct": 40, "sell_platform": "eBay", "flip_structure": "buy_upgrade_sell"},
        "ideal_build": {
            "cpu": {"candidate_models": ["Ryzen 5 5600", "i5-10400F", "i5-12400F"], "target_price": 50, "walk_away_price": 80,
                    "search_terms": ["ryzen 5 5600", "i5 10400f", "i5 12400f"], "negative_search_terms": ["faulty", "broken", "for parts"]},
            "gpu": {"candidate_models": ["RTX 3060", "RTX 3060 Ti", "RX 6600 XT"], "target_price": 90, "walk_away_price": 130,
                    "search_terms": ["rtx 3060", "rx 6600"], "negative_search_terms": ["faulty", "mining", "blower"]},
            "ram": {"candidate_models": ["16GB DDR4 3200MHz"], "target_price": 20, "walk_away_price": 35,
                    "search_terms": ["16gb ddr4 ram", "ddr4 3200"], "negative_search_terms": ["faulty", "untested"]},
            "storage": {"candidate_models": ["500GB NVMe SSD", "1TB NVMe SSD"], "target_price": 25, "walk_away_price": 45,
                        "search_terms": ["nvme ssd 500gb", "m.2 ssd 1tb"], "negative_search_terms": []},
            "psu": {"candidate_models": ["550W 80+ Bronze", "650W 80+ Bronze"], "target_price": 25, "walk_away_price": 45,
                    "search_terms": ["550w psu", "650w power supply"], "negative_search_terms": ["faulty", "no cable"]},
        },
        "seasonality": {"jan": 4, "feb": 3, "mar": 4, "apr": 4, "may": 5, "jun": 5, "jul": 5, "aug": 6,
                        "sep": 6, "oct": 7, "nov": 9, "dec": 10,
                        "peak_months": ["november", "december"], "slow_months": ["january", "february"],
                        "current_position": "approaching_peak", "days_until_peak": 150},
        "pricing_model": {"minimum_build_cost": 160, "expected_build_cost": 210, "maximum_build_cost": 280},
        "profit_model": {"minimum_profit": 60, "expected_profit": 100, "maximum_profit": 150, "expected_roi_pct": 48},
        "upgrade_strategy": {},
        "upsell_strategy": {},
        "component_catalogue": {},
    },
    {
        "name": "Mainstream Gamer",
        "emoji": "🖥️",
        "status": "active",
        "target_use_case": "gaming",
        "target_customer": "Most Buyers",
        "what_they_use_it_for": "1440p gaming, streaming, modern AAA titles, content consumption",
        "what_they_want_from_build": "Solid 1440p performance, reliable brand, looks decent, good price-to-performance",
        "critical_success_factors": ["1440p capable GPU", "Ryzen 5000/Intel 12th+ CPU", "16-32GB RAM", "NVMe storage"],
        "profit_opportunity_score": 5.0,
        "market_size_score": 9.0,
        "resellability_score": 9.0,
        "liquidity_score": 8.0,
        "risk_score": 3.0,
        "market_growth_direction": "Growing",
        "requirements": {"cpu_min_tier": "i5", "ram_min_gb": 16, "gpu_required": True, "psu_required": True},
        "search_strategy": {
            "keywords": ["gaming pc rtx 3070", "gaming pc rtx 3080", "gaming pc rx 6700", "custom gaming pc"],
            "price_min": 150, "price_max": 400, "listing_types": ["buy_it_now", "auction"]
        },
        "profit_strategy": {"target_profit_gbp": 140, "target_margin_pct": 38, "sell_platform": "eBay", "flip_structure": "buy_upgrade_sell"},
        "ideal_build": {
            "cpu": {"candidate_models": ["Ryzen 5 5600X", "Ryzen 7 5700X", "i5-12600K", "i5-13600K"], "target_price": 70, "walk_away_price": 110,
                    "search_terms": ["ryzen 7 5700x", "i5 12600k", "i5 13600k"], "negative_search_terms": ["faulty", "for parts"]},
            "gpu": {"candidate_models": ["RTX 3070", "RTX 3070 Ti", "RX 6700 XT", "RTX 4060 Ti"], "target_price": 140, "walk_away_price": 200,
                    "search_terms": ["rtx 3070", "rx 6700 xt", "rtx 4060 ti"], "negative_search_terms": ["mining", "faulty", "blower"]},
            "ram": {"candidate_models": ["32GB DDR4 3200MHz", "16GB DDR4 3600MHz"], "target_price": 30, "walk_away_price": 55,
                    "search_terms": ["32gb ddr4", "16gb ddr4 3600"], "negative_search_terms": []},
            "storage": {"candidate_models": ["1TB NVMe SSD"], "target_price": 35, "walk_away_price": 60,
                        "search_terms": ["1tb nvme ssd", "samsung 970 evo"], "negative_search_terms": []},
            "psu": {"candidate_models": ["650W 80+ Gold", "750W 80+ Gold"], "target_price": 40, "walk_away_price": 70,
                    "search_terms": ["650w gold psu", "750w modular psu"], "negative_search_terms": ["faulty"]},
        },
        "seasonality": {"jan": 5, "feb": 5, "mar": 6, "apr": 6, "may": 7, "jun": 7, "jul": 7, "aug": 7,
                        "sep": 7, "oct": 8, "nov": 10, "dec": 9,
                        "peak_months": ["october", "november"], "slow_months": ["january", "february"],
                        "current_position": "mid_season", "days_until_peak": 120},
        "pricing_model": {"minimum_build_cost": 230, "expected_build_cost": 315, "maximum_build_cost": 415},
        "profit_model": {"minimum_profit": 85, "expected_profit": 140, "maximum_profit": 210, "expected_roi_pct": 44},
        "upgrade_strategy": {},
        "upsell_strategy": {},
        "component_catalogue": {},
    },
    {
        "name": "RGB Showcase Build",
        "emoji": "🌈",
        "status": "active",
        "target_use_case": "gaming",
        "target_customer": "Impulse Buyers",
        "what_they_use_it_for": "Gaming, TikTok content, desk aesthetics, RGB lighting displays",
        "what_they_want_from_build": "Looks expensive, RGB everywhere, white aesthetic or black theme, fish tank case",
        "critical_success_factors": ["Tempered glass case", "RGB lighting", "White/black theme consistency", "Cable management", "Visually striking"],
        "profit_opportunity_score": 5.0,
        "market_size_score": 7.0,
        "resellability_score": 8.0,
        "liquidity_score": 7.0,
        "risk_score": 4.0,
        "market_growth_direction": "Growing",
        "requirements": {"cpu_min_tier": "Ryzen 5", "ram_min_gb": 16, "gpu_required": True, "psu_required": True},
        "search_strategy": {
            "keywords": ["white gaming pc", "rgb gaming pc", "gaming pc rgb", "showcase gaming pc build"],
            "price_min": 100, "price_max": 350, "listing_types": ["buy_it_now", "auction"]
        },
        "profit_strategy": {"target_profit_gbp": 130, "target_margin_pct": 42, "sell_platform": "eBay", "flip_structure": "buy_upgrade_sell",
                             "notes": "Presentation is everything. Good photos = 15-20% higher final price."},
        "ideal_build": {
            "cpu": {"candidate_models": ["Ryzen 5 5600", "Ryzen 7 5700X"], "target_price": 55, "walk_away_price": 85,
                    "search_terms": ["ryzen 5 5600", "ryzen 7 5700x"], "negative_search_terms": ["faulty"]},
            "gpu": {"candidate_models": ["RTX 3060 Ti", "RTX 3070", "RX 6700 XT"], "target_price": 120, "walk_away_price": 170,
                    "search_terms": ["rtx 3060 ti white", "rtx 3070 white", "white gpu"], "negative_search_terms": ["mining", "faulty"]},
            "ram": {"candidate_models": ["16GB DDR4 RGB", "32GB DDR4 RGB", "Corsair Vengeance RGB", "G.Skill Trident Z RGB"],
                    "target_price": 35, "walk_away_price": 65,
                    "search_terms": ["rgb ram ddr4", "corsair vengeance rgb", "gskill trident rgb"], "negative_search_terms": []},
            "case": {"candidate_models": ["Lian Li PC-O11", "NZXT H510 Elite", "Corsair 4000D Airflow White", "Phanteks P400A White"],
                     "target_price": 40, "walk_away_price": 80,
                     "search_terms": ["white gaming case", "rgb gaming case", "panoramic case", "fish tank case"], "negative_search_terms": ["damaged", "cracked"]},
            "storage": {"candidate_models": ["1TB NVMe SSD"], "target_price": 35, "walk_away_price": 55,
                        "search_terms": ["1tb nvme ssd"], "negative_search_terms": []},
            "psu": {"candidate_models": ["650W White PSU", "Corsair RM650 White"], "target_price": 45, "walk_away_price": 75,
                    "search_terms": ["white modular psu", "650w white power supply"], "negative_search_terms": ["faulty"]},
        },
        "seasonality": {"jan": 4, "feb": 4, "mar": 5, "apr": 6, "may": 6, "jun": 6, "jul": 7, "aug": 7,
                        "sep": 7, "oct": 8, "nov": 10, "dec": 9,
                        "peak_months": ["november", "december"], "slow_months": ["january", "february"],
                        "current_position": "mid_season", "days_until_peak": 145},
        "pricing_model": {"minimum_build_cost": 200, "expected_build_cost": 330, "maximum_build_cost": 475},
        "profit_model": {"minimum_profit": 80, "expected_profit": 130, "maximum_profit": 200, "expected_roi_pct": 39},
        "upgrade_strategy": {},
        "upsell_strategy": {},
        "component_catalogue": {},
    },
    {
        "name": "Competitive Gaming Build",
        "emoji": "⚡",
        "status": "active",
        "target_use_case": "gaming",
        "target_customer": "FPS Crowd",
        "what_they_use_it_for": "CS2, Valorant, Apex Legends, Rainbow Six, maximum FPS at 1080p",
        "what_they_want_from_build": "Maximum FPS, low latency, fast RAM, strong gaming CPU, strong GPU",
        "critical_success_factors": ["High clock speed CPU", "Fast DDR4/DDR5 RAM", "240Hz+ capable GPU", "Low latency"],
        "profit_opportunity_score": 4.0,
        "market_size_score": 7.0,
        "resellability_score": 7.0,
        "liquidity_score": 7.0,
        "risk_score": 3.0,
        "market_growth_direction": "Stable",
        "requirements": {"cpu_min_tier": "i5", "ram_min_gb": 16, "gpu_required": True, "psu_required": True},
        "search_strategy": {
            "keywords": ["gaming pc 144hz", "competitive gaming pc", "esports pc build", "cs2 gaming pc"],
            "price_min": 120, "price_max": 350, "listing_types": ["buy_it_now", "auction"]
        },
        "profit_strategy": {"target_profit_gbp": 120, "target_margin_pct": 38, "sell_platform": "eBay", "flip_structure": "buy_upgrade_sell"},
        "ideal_build": {
            "cpu": {"candidate_models": ["Ryzen 5 5600X", "Ryzen 7 5800X3D", "i5-12600K", "i5-13600K"],
                    "target_price": 75, "walk_away_price": 120,
                    "search_terms": ["ryzen 5 5600x", "ryzen 7 5800x3d", "i5 12600k"], "negative_search_terms": ["faulty"]},
            "gpu": {"candidate_models": ["RTX 3060 Ti", "RTX 3070", "RX 6700 XT"],
                    "target_price": 110, "walk_away_price": 165,
                    "search_terms": ["rtx 3060 ti", "rtx 3070", "rx 6700 xt"], "negative_search_terms": ["mining", "faulty"]},
            "ram": {"candidate_models": ["16GB DDR4 3600MHz CL16", "32GB DDR4 3600MHz"],
                    "target_price": 30, "walk_away_price": 55,
                    "search_terms": ["ddr4 3600mhz", "fast gaming ram", "cl16 ddr4"], "negative_search_terms": []},
            "storage": {"candidate_models": ["500GB NVMe Gen4", "1TB NVMe Gen4"],
                        "target_price": 30, "walk_away_price": 55,
                        "search_terms": ["gen4 nvme", "fast nvme ssd"], "negative_search_terms": []},
            "psu": {"candidate_models": ["650W 80+ Gold"],
                    "target_price": 35, "walk_away_price": 60,
                    "search_terms": ["650w gold psu"], "negative_search_terms": ["faulty"]},
        },
        "seasonality": {"jan": 5, "feb": 5, "mar": 6, "apr": 6, "may": 7, "jun": 8, "jul": 8, "aug": 7,
                        "sep": 7, "oct": 8, "nov": 9, "dec": 8,
                        "peak_months": ["june", "july", "november"], "slow_months": ["january", "february"],
                        "current_position": "in_season", "days_until_peak": 60},
        "pricing_model": {"minimum_build_cost": 200, "expected_build_cost": 280, "maximum_build_cost": 400},
        "profit_model": {"minimum_profit": 75, "expected_profit": 120, "maximum_profit": 185, "expected_roi_pct": 43},
        "upgrade_strategy": {},
        "upsell_strategy": {},
        "component_catalogue": {},
    },
    {
        "name": "Student Build",
        "emoji": "🎓",
        "status": "active",
        "target_use_case": "budget",
        "target_customer": "University Students",
        "what_they_use_it_for": "Assignments, light gaming, streaming, Discord, Zoom calls, coding basics",
        "what_they_want_from_build": "Reliable, fast enough for multitasking, SSD for boot speed, budget",
        "critical_success_factors": ["Fast SSD", "8-16GB RAM", "Reliable CPU", "Price under £250", "Good for productivity"],
        "profit_opportunity_score": 4.0,
        "market_size_score": 8.0,
        "resellability_score": 7.0,
        "liquidity_score": 8.0,
        "risk_score": 3.0,
        "market_growth_direction": "Stable",
        "requirements": {"cpu_min_tier": "i5", "ram_min_gb": 8, "gpu_required": False, "psu_required": True},
        "search_strategy": {
            "keywords": ["student pc", "office pc no gpu", "HP EliteDesk", "Dell OptiPlex", "ex office pc"],
            "price_min": 30, "price_max": 130, "listing_types": ["buy_it_now", "auction"]
        },
        "profit_strategy": {"target_profit_gbp": 70, "target_margin_pct": 45, "sell_platform": "eBay", "flip_structure": "buy_clean_sell",
                             "notes": "Clean up, add SSD if missing, price at £150-200 for quick sale."},
        "ideal_build": {
            "cpu": {"candidate_models": ["i5-8500", "i5-9400", "i5-10400", "Ryzen 5 3600"],
                    "target_price": 20, "walk_away_price": 40,
                    "search_terms": ["i5 office pc", "dell optiplex i5", "hp elitedesk i5"], "negative_search_terms": ["faulty", "no power"]},
            "ram": {"candidate_models": ["8GB DDR4", "16GB DDR4"],
                    "target_price": 10, "walk_away_price": 20,
                    "search_terms": ["8gb ddr4 ram", "16gb ddr4"], "negative_search_terms": []},
            "storage": {"candidate_models": ["256GB SSD", "500GB SSD"],
                        "target_price": 15, "walk_away_price": 30,
                        "search_terms": ["256gb ssd", "500gb ssd sata"], "negative_search_terms": []},
            "psu": {"candidate_models": ["SFF PSU 260W", "Slim PSU 300W"],
                    "target_price": 10, "walk_away_price": 20,
                    "search_terms": ["sff psu", "small form factor power supply"], "negative_search_terms": ["faulty"]},
        },
        "seasonality": {"jan": 3, "feb": 4, "mar": 5, "apr": 5, "may": 6, "jun": 6, "jul": 7, "aug": 10,
                        "sep": 9, "oct": 7, "nov": 6, "dec": 5,
                        "peak_months": ["august", "september"], "slow_months": ["january", "february"],
                        "current_position": "approaching_peak", "days_until_peak": 75},
        "pricing_model": {"minimum_build_cost": 55, "expected_build_cost": 85, "maximum_build_cost": 110},
        "profit_model": {"minimum_profit": 40, "expected_profit": 70, "maximum_profit": 100, "expected_roi_pct": 82},
        "upgrade_strategy": {},
        "upsell_strategy": {},
        "component_catalogue": {},
    },
    {
        "name": "Developer Workstation",
        "emoji": "💻",
        "status": "active",
        "target_use_case": "workstation",
        "target_customer": "Developers",
        "what_they_use_it_for": "Docker, virtual machines, databases, local services, VS Code, coding agents, Node.js, Python",
        "what_they_want_from_build": "Core count, RAM capacity (32GB+), NVMe speed and capacity, reliability, ECC if possible",
        "critical_success_factors": ["8+ core CPU", "32GB+ RAM", "Fast NVMe 1TB+", "Reliable brand", "Good thermals"],
        "profit_opportunity_score": 3.0,
        "market_size_score": 6.0,
        "resellability_score": 6.0,
        "liquidity_score": 5.0,
        "risk_score": 4.0,
        "market_growth_direction": "Growing",
        "requirements": {"cpu_min_tier": "i7", "ram_min_gb": 32, "gpu_required": False, "psu_required": True},
        "search_strategy": {
            "keywords": ["hp workstation", "dell precision", "workstation pc", "hp z440", "hp z640", "threadripper workstation"],
            "price_min": 80, "price_max": 300, "listing_types": ["buy_it_now", "auction"]
        },
        "profit_strategy": {"target_profit_gbp": 110, "target_margin_pct": 35, "sell_platform": "eBay", "flip_structure": "buy_upgrade_sell"},
        "ideal_build": {
            "cpu": {"candidate_models": ["Ryzen 7 5700X", "Ryzen 9 5900X", "i7-10700K", "Xeon E5-2690 v4"],
                    "target_price": 80, "walk_away_price": 130,
                    "search_terms": ["ryzen 9 5900x", "i7 10700k", "xeon e5"], "negative_search_terms": ["faulty", "damaged"]},
            "ram": {"candidate_models": ["32GB DDR4 ECC", "64GB DDR4", "32GB DDR4 3200MHz"],
                    "target_price": 40, "walk_away_price": 80,
                    "search_terms": ["32gb ddr4 ecc", "64gb ddr4 workstation"], "negative_search_terms": []},
            "storage": {"candidate_models": ["1TB NVMe SSD", "2TB NVMe SSD"],
                        "target_price": 40, "walk_away_price": 70,
                        "search_terms": ["1tb nvme", "2tb nvme ssd"], "negative_search_terms": []},
            "psu": {"candidate_models": ["750W 80+ Gold", "850W 80+ Gold"],
                    "target_price": 40, "walk_away_price": 70,
                    "search_terms": ["750w gold psu", "850w psu"], "negative_search_terms": ["faulty"]},
        },
        "seasonality": {"jan": 7, "feb": 7, "mar": 8, "apr": 8, "may": 8, "jun": 8, "jul": 7, "aug": 7,
                        "sep": 8, "oct": 8, "nov": 7, "dec": 6,
                        "peak_months": ["march", "april", "september"], "slow_months": ["december"],
                        "current_position": "in_season", "days_until_peak": 0},
        "pricing_model": {"minimum_build_cost": 200, "expected_build_cost": 350, "maximum_build_cost": 500},
        "profit_model": {"minimum_profit": 70, "expected_profit": 110, "maximum_profit": 180, "expected_roi_pct": 31},
        "upgrade_strategy": {},
        "upsell_strategy": {},
        "component_catalogue": {},
    },
    {
        "name": "AI Workstation",
        "emoji": "🤖",
        "status": "active",
        "target_use_case": "ai_workstation",
        "target_customer": "LLM / AI Users",
        "what_they_use_it_for": "Ollama, Open WebUI, local LLMs, Stable Diffusion, AI agent workloads, llama.cpp",
        "what_they_want_from_build": "VRAM (24GB+), system RAM (32-64GB), CPU threads, upgradeability",
        "critical_success_factors": ["GPU VRAM 12GB+", "32GB+ system RAM", "Multiple PCIe lanes", "Good cooling", "Upgradeability"],
        "profit_opportunity_score": 3.0,
        "market_size_score": 7.0,
        "resellability_score": 7.0,
        "liquidity_score": 5.0,
        "risk_score": 4.0,
        "market_growth_direction": "Growing",
        "requirements": {"cpu_min_tier": "i7", "ram_min_gb": 32, "gpu_required": True, "psu_required": True},
        "search_strategy": {
            "keywords": ["ai workstation", "rtx 3090 pc", "rtx 4090 pc", "local llm pc", "ml workstation", "ai pc"],
            "price_min": 200, "price_max": 800, "listing_types": ["buy_it_now", "auction"]
        },
        "profit_strategy": {"target_profit_gbp": 150, "target_margin_pct": 30, "sell_platform": "eBay", "flip_structure": "buy_upgrade_sell",
                             "notes": "AI market growing fast. Buyers pay premium for VRAM. Target developers and AI hobbyists."},
        "ideal_build": {
            "cpu": {"candidate_models": ["Ryzen 9 5900X", "Ryzen 9 7900X", "i9-12900K"],
                    "target_price": 100, "walk_away_price": 160,
                    "search_terms": ["ryzen 9 5900x", "i9 12900k"], "negative_search_terms": ["faulty"]},
            "gpu": {"candidate_models": ["RTX 3090", "RTX 4090", "RTX 3090 Ti", "RTX 4080"],
                    "target_price": 300, "walk_away_price": 500,
                    "search_terms": ["rtx 3090", "rtx 4090", "24gb vram gpu"], "negative_search_terms": ["faulty", "mining", "blower"]},
            "ram": {"candidate_models": ["64GB DDR4", "128GB DDR4 ECC"],
                    "target_price": 60, "walk_away_price": 110,
                    "search_terms": ["64gb ddr4", "128gb ddr4 ecc server ram"], "negative_search_terms": []},
            "storage": {"candidate_models": ["2TB NVMe SSD", "4TB NVMe SSD"],
                        "target_price": 70, "walk_away_price": 120,
                        "search_terms": ["2tb nvme", "4tb nvme ssd"], "negative_search_terms": []},
            "psu": {"candidate_models": ["1000W 80+ Gold", "1200W 80+ Platinum"],
                    "target_price": 60, "walk_away_price": 100,
                    "search_terms": ["1000w psu", "1200w platinum psu"], "negative_search_terms": ["faulty"]},
        },
        "seasonality": {"jan": 7, "feb": 8, "mar": 8, "apr": 9, "may": 9, "jun": 9, "jul": 8, "aug": 8,
                        "sep": 8, "oct": 8, "nov": 8, "dec": 7,
                        "peak_months": ["april", "may", "june"], "slow_months": ["december"],
                        "current_position": "in_peak", "days_until_peak": 0},
        "pricing_model": {"minimum_build_cost": 530, "expected_build_cost": 590, "maximum_build_cost": 890},
        "profit_model": {"minimum_profit": 90, "expected_profit": 150, "maximum_profit": 270, "expected_roi_pct": 25},
        "upgrade_strategy": {},
        "upsell_strategy": {},
        "component_catalogue": {},
    },
    {
        "name": "Content Creator",
        "emoji": "🎬",
        "status": "active",
        "target_use_case": "workstation",
        "target_customer": "Streamers / Editors",
        "what_they_use_it_for": "Adobe Premiere, DaVinci Resolve, OBS streaming, After Effects, Photoshop, YouTube",
        "what_they_want_from_build": "Fast CPU for rendering, dedicated GPU for encoding, 32GB+ RAM, fast storage",
        "critical_success_factors": ["Fast multi-core CPU", "32GB RAM", "GPU with NVENC/HEVC", "Fast 2TB+ storage", "Reliable"],
        "profit_opportunity_score": 3.0,
        "market_size_score": 6.0,
        "resellability_score": 6.0,
        "liquidity_score": 5.0,
        "risk_score": 4.0,
        "market_growth_direction": "Growing",
        "requirements": {"cpu_min_tier": "i7", "ram_min_gb": 32, "gpu_required": True, "psu_required": True},
        "search_strategy": {
            "keywords": ["content creator pc", "video editing pc", "streaming pc", "ryzen 9 desktop", "i9 desktop"],
            "price_min": 120, "price_max": 400, "listing_types": ["buy_it_now", "auction"]
        },
        "profit_strategy": {"target_profit_gbp": 130, "target_margin_pct": 35, "sell_platform": "eBay", "flip_structure": "buy_upgrade_sell"},
        "ideal_build": {
            "cpu": {"candidate_models": ["Ryzen 9 5900X", "Ryzen 9 5950X", "i9-10900K", "i9-12900K"],
                    "target_price": 100, "walk_away_price": 160,
                    "search_terms": ["ryzen 9 5900x", "i9 10900k", "i9 12900k"], "negative_search_terms": ["faulty"]},
            "gpu": {"candidate_models": ["RTX 3070 Ti", "RTX 3080", "RTX 4070"],
                    "target_price": 170, "walk_away_price": 260,
                    "search_terms": ["rtx 3080", "rtx 4070", "rtx 3070 ti"], "negative_search_terms": ["mining", "faulty"]},
            "ram": {"candidate_models": ["32GB DDR4", "64GB DDR4"],
                    "target_price": 40, "walk_away_price": 75,
                    "search_terms": ["32gb ddr4", "64gb ddr4"], "negative_search_terms": []},
            "storage": {"candidate_models": ["2TB NVMe SSD", "2TB Samsung 970 Evo"],
                        "target_price": 55, "walk_away_price": 90,
                        "search_terms": ["2tb nvme ssd", "samsung 970 evo 2tb"], "negative_search_terms": []},
            "psu": {"candidate_models": ["850W 80+ Gold", "1000W 80+ Gold"],
                    "target_price": 50, "walk_away_price": 85,
                    "search_terms": ["850w gold psu", "1000w psu"], "negative_search_terms": ["faulty"]},
        },
        "seasonality": {"jan": 5, "feb": 5, "mar": 6, "apr": 7, "may": 7, "jun": 7, "jul": 7, "aug": 7,
                        "sep": 7, "oct": 8, "nov": 9, "dec": 8,
                        "peak_months": ["october", "november"], "slow_months": ["january", "february"],
                        "current_position": "mid_season", "days_until_peak": 120},
        "pricing_model": {"minimum_build_cost": 320, "expected_build_cost": 415, "maximum_build_cost": 610},
        "profit_model": {"minimum_profit": 80, "expected_profit": 130, "maximum_profit": 215, "expected_roi_pct": 31},
        "upgrade_strategy": {},
        "upsell_strategy": {},
        "component_catalogue": {},
    },
    {
        "name": "Ultra Budget Flip",
        "emoji": "💰",
        "status": "active",
        "target_use_case": "budget",
        "target_customer": "Facebook Marketplace Buyers",
        "what_they_use_it_for": "Basic web browsing, word processing, email, light media, kids' first PC",
        "what_they_want_from_build": "Just works, cheap price, SSD is a bonus, anything under £150",
        "critical_success_factors": ["Price under £150", "Working condition", "Fast boot SSD", "Clean install Windows"],
        "profit_opportunity_score": 4.0,
        "market_size_score": 9.0,
        "resellability_score": 8.0,
        "liquidity_score": 10.0,
        "risk_score": 2.0,
        "market_growth_direction": "Stable",
        "requirements": {"cpu_min_tier": "i3", "ram_min_gb": 4, "gpu_required": False, "psu_required": True},
        "search_strategy": {
            "keywords": ["job lot pcs", "bulk office pcs", "ex lease pc", "computer bundle", "joblot computers", "pc lot clearance"],
            "price_min": 5, "price_max": 60, "listing_types": ["buy_it_now", "auction"]
        },
        "profit_strategy": {"target_profit_gbp": 50, "target_margin_pct": 55, "sell_platform": "eBay", "flip_structure": "buy_clean_sell",
                             "notes": "Buy lots of 5-10, clean and sell individually. High volume, low margin per unit."},
        "ideal_build": {
            "cpu": {"candidate_models": ["i3-8100", "i5-7500", "i5-8400", "i3-10100"],
                    "target_price": 8, "walk_away_price": 20,
                    "search_terms": ["job lot pcs", "bulk pcs office", "i5 desktop lot"], "negative_search_terms": ["no hdd only", "scrap", "water damaged"]},
            "ram": {"candidate_models": ["4GB DDR4", "8GB DDR4"],
                    "target_price": 5, "walk_away_price": 12,
                    "search_terms": ["4gb ddr4 lot", "8gb ddr4 used"], "negative_search_terms": []},
            "storage": {"candidate_models": ["120GB SSD", "240GB SSD"],
                        "target_price": 8, "walk_away_price": 18,
                        "search_terms": ["120gb ssd lot", "240gb ssd"], "negative_search_terms": []},
        },
        "seasonality": {"jan": 6, "feb": 6, "mar": 7, "apr": 7, "may": 7, "jun": 7, "jul": 7, "aug": 8,
                        "sep": 8, "oct": 8, "nov": 9, "dec": 9,
                        "peak_months": ["november", "december", "august"], "slow_months": [],
                        "current_position": "in_season", "days_until_peak": 0},
        "pricing_model": {"minimum_build_cost": 21, "expected_build_cost": 30, "maximum_build_cost": 50},
        "profit_model": {"minimum_profit": 30, "expected_profit": 50, "maximum_profit": 80, "expected_roi_pct": 167},
        "upgrade_strategy": {},
        "upsell_strategy": {},
        "component_catalogue": {},
    },
    {
        "name": "Premium Showcase",
        "emoji": "👑",
        "status": "active",
        "target_use_case": "gaming",
        "target_customer": "High-end Buyers",
        "what_they_use_it_for": "4K gaming, VR, content creation, prestige ownership, top-tier performance",
        "what_they_want_from_build": "Best-in-class specs, premium case, 4K capable GPU, looks impressive",
        "critical_success_factors": ["RTX 4080/4090 GPU", "Latest gen CPU", "DDR5 RAM", "Premium case", "Premium brand parts"],
        "profit_opportunity_score": 2.0,
        "market_size_score": 4.0,
        "resellability_score": 5.0,
        "liquidity_score": 3.0,
        "risk_score": 7.0,
        "market_growth_direction": "Stable",
        "requirements": {"cpu_min_tier": "i9", "ram_min_gb": 32, "gpu_required": True, "psu_required": True},
        "search_strategy": {
            "keywords": ["rtx 4090 pc", "rtx 4080 gaming pc", "high end gaming pc", "threadripper build"],
            "price_min": 500, "price_max": 2000, "listing_types": ["buy_it_now"]
        },
        "profit_strategy": {"target_profit_gbp": 200, "target_margin_pct": 25, "sell_platform": "eBay", "flip_structure": "buy_upgrade_sell",
                             "notes": "High value, slower sales. Needs premium listing photos and detailed spec sheet."},
        "ideal_build": {
            "cpu": {"candidate_models": ["i9-13900K", "i9-14900K", "Ryzen 9 7950X", "Ryzen 9 7900X3D"],
                    "target_price": 200, "walk_away_price": 320,
                    "search_terms": ["i9 13900k", "ryzen 9 7950x"], "negative_search_terms": ["faulty"]},
            "gpu": {"candidate_models": ["RTX 4090", "RTX 4080", "RTX 4080 Super"],
                    "target_price": 600, "walk_away_price": 900,
                    "search_terms": ["rtx 4090", "rtx 4080"], "negative_search_terms": ["faulty", "mining"]},
            "ram": {"candidate_models": ["32GB DDR5 6000MHz", "64GB DDR5"],
                    "target_price": 80, "walk_away_price": 140,
                    "search_terms": ["ddr5 32gb", "ddr5 6000mhz ram"], "negative_search_terms": []},
            "storage": {"candidate_models": ["2TB NVMe Gen5", "4TB NVMe SSD"],
                        "target_price": 100, "walk_away_price": 170,
                        "search_terms": ["gen5 nvme 2tb", "4tb nvme ssd"], "negative_search_terms": []},
            "case": {"candidate_models": ["Lian Li O11 XL", "Phanteks Enthoo 719", "Corsair 7000D"],
                     "target_price": 80, "walk_away_price": 150,
                     "search_terms": ["premium gaming case", "full tower case", "lian li o11"], "negative_search_terms": ["damaged", "cracked"]},
            "psu": {"candidate_models": ["1200W 80+ Platinum", "1000W 80+ Titanium"],
                    "target_price": 100, "walk_away_price": 170,
                    "search_terms": ["1200w platinum psu", "1000w titanium psu"], "negative_search_terms": ["faulty"]},
        },
        "seasonality": {"jan": 4, "feb": 4, "mar": 4, "apr": 5, "may": 5, "jun": 5, "jul": 5, "aug": 5,
                        "sep": 5, "oct": 6, "nov": 9, "dec": 10,
                        "peak_months": ["november", "december"], "slow_months": ["january", "february", "march"],
                        "current_position": "slow_season", "days_until_peak": 160},
        "pricing_model": {"minimum_build_cost": 1080, "expected_build_cost": 1160, "maximum_build_cost": 1700},
        "profit_model": {"minimum_profit": 120, "expected_profit": 200, "maximum_profit": 425, "expected_roi_pct": 17},
        "upgrade_strategy": {},
        "upsell_strategy": {},
        "component_catalogue": {},
    },
]


async def seed_playbooks(db: AsyncSession) -> int:
    """Insert any of the 10 canonical playbooks that don't already exist. Returns count created."""
    from datetime import datetime as dt
    created = 0
    for data in _INITIAL_PLAYBOOKS:
        result = await db.execute(
            select(Playbook).where(Playbook.name == data["name"])
        )
        if result.scalar_one_or_none() is not None:
            continue
        pb = Playbook(
            **data,
            activated_at=dt.utcnow(),
        )
        db.add(pb)
        created += 1
    await db.commit()
    return created
