"""playbook_rich_authoring_fields

Revision ID: 573cf6989b91
Revises: edc72af6d2bb
Create Date: 2026-07-02 00:02:29.193921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '573cf6989b91'
down_revision: Union[str, None] = 'edc72af6d2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playbooks', sa.Column('what_they_use_it_for', sa.Text(), nullable=True))
    op.add_column('playbooks', sa.Column('what_they_want_from_build', sa.Text(), nullable=True))
    op.add_column('playbooks', sa.Column('critical_success_factors', sa.JSON(), nullable=True))
    op.add_column('playbooks', sa.Column('profit_opportunity_score', sa.Float(), nullable=True))
    op.add_column('playbooks', sa.Column('market_size_score', sa.Float(), nullable=True))
    op.add_column('playbooks', sa.Column('resellability_score', sa.Float(), nullable=True))
    op.add_column('playbooks', sa.Column('liquidity_score', sa.Float(), nullable=True))
    op.add_column('playbooks', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('playbooks', sa.Column('market_growth_direction', sa.String(), nullable=True))
    op.add_column('playbooks', sa.Column('requirements', sa.JSON(), nullable=True))
    op.add_column('playbooks', sa.Column('search_strategy', sa.JSON(), nullable=True))
    op.add_column('playbooks', sa.Column('profit_strategy', sa.JSON(), nullable=True))
    op.add_column('playbooks', sa.Column('ideal_build', sa.JSON(), nullable=True))
    op.add_column('playbooks', sa.Column('seasonality', sa.JSON(), nullable=True))
    op.add_column('playbooks', sa.Column('pricing_model', sa.JSON(), nullable=True))
    op.add_column('playbooks', sa.Column('profit_model', sa.JSON(), nullable=True))
    op.add_column('playbooks', sa.Column('upgrade_strategy', sa.JSON(), nullable=True))
    op.add_column('playbooks', sa.Column('component_catalogue', sa.JSON(), nullable=True))
    op.alter_column('playbooks', 'target_budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('playbooks', 'specs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playbooks', 'specs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('playbooks', 'target_budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('playbooks', 'component_catalogue')
    op.drop_column('playbooks', 'upgrade_strategy')
    op.drop_column('playbooks', 'profit_model')
    op.drop_column('playbooks', 'pricing_model')
    op.drop_column('playbooks', 'seasonality')
    op.drop_column('playbooks', 'ideal_build')
    op.drop_column('playbooks', 'profit_strategy')
    op.drop_column('playbooks', 'search_strategy')
    op.drop_column('playbooks', 'requirements')
    op.drop_column('playbooks', 'market_growth_direction')
    op.drop_column('playbooks', 'risk_score')
    op.drop_column('playbooks', 'liquidity_score')
    op.drop_column('playbooks', 'resellability_score')
    op.drop_column('playbooks', 'market_size_score')
    op.drop_column('playbooks', 'profit_opportunity_score')
    op.drop_column('playbooks', 'critical_success_factors')
    op.drop_column('playbooks', 'what_they_want_from_build')
    op.drop_column('playbooks', 'what_they_use_it_for')
    # ### end Alembic commands ###
