"""phase0_commerce_and_cxp_schema

Revision ID: edc72af6d2bb
Revises: 20260629_0013
Create Date: 2026-07-01 23:55:17.946488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edc72af6d2bb'
down_revision: Union[str, None] = '20260629_0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bi_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('PROFITABILITY', 'CLV', 'UPGRADE_CONVERSION', 'PACKAGING_COST', 'SUPPLIER_PERFORMANCE', 'REPEAT_PURCHASE', 'REVIEW_SENTIMENT', 'INVENTORY', name='bicategory'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('supporting_data_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'ACTIONED', 'DISMISSED', name='birecommendationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cx_document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('BUILD_CERTIFICATE', 'CAPTAINS_LOG', 'BENCHMARK_REPORT', 'GETTING_STARTED_GUIDE', 'UPGRADE_GUIDE', 'WARRANTY_PACK', 'QR_CODE_CARD', 'WELCOME_LETTER', 'ACCESSORY_CHECKLIST', 'USB_MANIFEST', name='cxdocumenttype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', name='cxdocumenttemplatestatus'), nullable=False),
    sa.Column('layout_spec', sa.JSON(), nullable=True),
    sa.Column('is_shipment_blocking', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('uk_warehouse', sa.Boolean(), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), nullable=True),
    sa.Column('integration_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_suppliers_name'), 'procurement_suppliers', ['name'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.Enum('PREBUILT', 'CONFIGURABLE_TEMPLATE', name='producttype'), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('playbook_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'LISTED', 'RESERVED', 'SOLD', 'WITHDRAWN', name='productstatus'), nullable=False),
    sa.Column('sold_via_channel', sa.Enum('EBAY', 'STOREFRONT', name='soldchannel'), nullable=True),
    sa.Column('sold_order_id', sa.Integer(), nullable=True),
    sa.Column('benchmark_report_document_id', sa.Integer(), nullable=True),
    sa.Column('capture_3d_asset_id', sa.Integer(), nullable=True),
    sa.Column('hero_photo_url', sa.String(), nullable=True),
    sa.Column('profit_calculation_id', sa.Integer(), nullable=True),
    sa.Column('reserved_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.ForeignKeyConstraint(['sold_order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profit_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('component_cost', sa.Float(), nullable=True),
    sa.Column('cx_cost', sa.Float(), nullable=True),
    sa.Column('channel_fee', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('margin_pct', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profit_calculations_order_id'), 'profit_calculations', ['order_id'], unique=False)
    op.create_index(op.f('ix_profit_calculations_product_id'), 'profit_calculations', ['product_id'], unique=False)
    op.create_table('packaging_playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', name='packagingplaybookstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('carton_spec', sa.JSON(), nullable=True),
    sa.Column('protection_spec', sa.JSON(), nullable=True),
    sa.Column('void_fill_spec', sa.JSON(), nullable=True),
    sa.Column('security_spec', sa.JSON(), nullable=True),
    sa.Column('label_spec', sa.JSON(), nullable=True),
    sa.Column('documentation_pack', sa.JSON(), nullable=True),
    sa.Column('captains_log_spec', sa.JSON(), nullable=True),
    sa.Column('usb_content_spec', sa.JSON(), nullable=True),
    sa.Column('welcome_gifts', sa.JSON(), nullable=True),
    sa.Column('accessories', sa.JSON(), nullable=True),
    sa.Column('premium_extras', sa.JSON(), nullable=True),
    sa.Column('presentation_order', sa.JSON(), nullable=True),
    sa.Column('unboxing_sequence', sa.JSON(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('estimated_labour_minutes', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_playbooks_name'), 'packaging_playbooks', ['name'], unique=True)
    op.create_index(op.f('ix_packaging_playbooks_slug'), 'packaging_playbooks', ['slug'], unique=True)
    op.create_table('procurement_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('CARTON', 'PROTECTION', 'VOID_FILL', 'SECURITY', 'LABEL', 'GIFT', 'ACCESSORY', 'PREMIUM_EXTRA', name='packagingcomponentcategory'), nullable=False),
    sa.Column('unit_of_measure', sa.String(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('preferred_supplier_id', sa.Integer(), nullable=True),
    sa.Column('purchase_url', sa.String(), nullable=True),
    sa.Column('min_stock_level', sa.Integer(), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('spec_json', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['preferred_supplier_id'], ['procurement_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_procurement_products_name'), 'procurement_products', ['name'], unique=False)
    op.create_table('product_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EBAY', 'STOREFRONT', name='listingchannel'), nullable=False),
    sa.Column('external_listing_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SOLD', 'WITHDRAWN', 'FAILED', name='productlistingstatus'), nullable=False),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('withdrawal_reason', sa.Enum('SOLD_OTHER_CHANNEL', 'MANUAL', 'EXPIRED', 'ERROR', name='withdrawalreason'), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('watcher_count', sa.Integer(), nullable=True),
    sa.Column('offer_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_listings_product_id'), 'product_listings', ['product_id'], unique=False)
    op.create_table('channel_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_listing_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('OFFER_RECEIVED', 'QUESTION_RECEIVED', 'WATCHER_ADDED', 'BASKET_ADDED', 'SALE_CONFIRMED', 'PAYMENT_CONFIRMED', name='channeleventtype'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('resulting_action', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_listing_id'], ['product_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_events_product_listing_id'), 'channel_events', ['product_listing_id'], unique=False)
    op.create_table('packaging_playbook_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packaging_playbook_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('CARTON', 'PROTECTION', 'VOID_FILL', 'SECURITY', 'LABEL', 'GIFT', 'ACCESSORY', 'PREMIUM_EXTRA', name='packagingcomponentcategory'), nullable=False),
    sa.Column('procurement_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_snapshot', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['packaging_playbook_id'], ['packaging_playbooks.id'], ),
    sa.ForeignKeyConstraint(['procurement_product_id'], ['procurement_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_playbook_components_packaging_playbook_id'), 'packaging_playbook_components', ['packaging_playbook_id'], unique=False)
    op.create_table('packaging_playbook_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packaging_playbook_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['packaging_playbook_id'], ['packaging_playbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packaging_playbook_versions_packaging_playbook_id'), 'packaging_playbook_versions', ['packaging_playbook_id'], unique=False)
    op.create_table('photo_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packaging_playbook_id', sa.Integer(), nullable=True),
    sa.Column('photo_type', sa.Enum('ASSEMBLY', 'COMPLETION', 'PACKAGING', 'FINAL_BOXED', name='phototype'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['packaging_playbook_id'], ['packaging_playbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement_product_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procurement_product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_sku', sa.String(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('lead_time_days_override', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['procurement_product_id'], ['procurement_products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['procurement_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_product_suppliers_procurement_product_id'), 'procurement_product_suppliers', ['procurement_product_id'], unique=False)
    op.create_table('procurement_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procurement_product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_paid', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['procurement_product_id'], ['procurement_products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['procurement_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_purchases_procurement_product_id'), 'procurement_purchases', ['procurement_product_id'], unique=False)
    op.create_table('quality_gate_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packaging_playbook_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('requires_evidence', sa.Enum('NONE', 'PHOTO', 'SIGNATURE', 'PHOTO_AND_SIGNATURE', name='evidencerequirement'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['packaging_playbook_id'], ['packaging_playbooks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('usb_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('linked_playbook_id', sa.Integer(), nullable=True),
    sa.Column('content_categories', sa.JSON(), nullable=True),
    sa.Column('static_file_refs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linked_playbook_id'], ['playbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_type', sa.Enum('FLIP', 'MADE_TO_ORDER', name='buildtype'), nullable=False),
    sa.Column('flip_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('playbook_id', sa.Integer(), nullable=True),
    sa.Column('spec_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'SOURCING', 'MANUFACTURING', 'FINALISED', 'CANCELLED', name='buildstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flip_id'], ['flips.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capture_3d_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CAPTURED', 'OPTIMIZING', 'OPTIMIZED', 'PUBLISHED', 'FAILED', name='capture3dstatus'), nullable=False),
    sa.Column('raw_asset_ref', sa.String(), nullable=True),
    sa.Column('optimized_asset_ref', sa.String(), nullable=True),
    sa.Column('preview_image_ref', sa.String(), nullable=True),
    sa.Column('ar_ready', sa.Boolean(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('optimized_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('compatibility_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('SOCKET_MATCH', 'FORM_FACTOR_FIT', 'PSU_WATTAGE_MIN', 'CLEARANCE_MAX', 'RAM_TYPE_MATCH', 'CUSTOM', name='compatibilityruletype'), nullable=False),
    sa.Column('subject_slot_id', sa.Integer(), nullable=False),
    sa.Column('constraint_json', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_slot_id'], ['playbook_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cx_cost_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('packaging_cost', sa.Float(), nullable=True),
    sa.Column('consumables_cost', sa.Float(), nullable=True),
    sa.Column('accessories_cost', sa.Float(), nullable=True),
    sa.Column('documentation_cost', sa.Float(), nullable=True),
    sa.Column('usb_cost', sa.Float(), nullable=True),
    sa.Column('shipping_handling_cost', sa.Float(), nullable=True),
    sa.Column('labour_cost', sa.Float(), nullable=True),
    sa.Column('total_cx_cost', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('cx_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('BUILD_CERTIFICATE', 'CAPTAINS_LOG', 'BENCHMARK_REPORT', 'GETTING_STARTED_GUIDE', 'UPGRADE_GUIDE', 'WARRANTY_PACK', 'QR_CODE_CARD', 'WELCOME_LETTER', 'ACCESSORY_CHECKLIST', 'USB_MANIFEST', name='cxdocumenttype'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('GENERATING', 'READY', 'FAILED', 'SUPERSEDED', name='cxdocumentstatus'), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('pdf_blob', sa.LargeBinary(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.Enum('SYSTEM', 'OPERATOR', name='cxdocumentgeneratedby'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['cx_document_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cx_documents_order_id'), 'cx_documents', ['order_id'], unique=False)
    op.create_table('lifecycle_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('DELIVERY_CONFIRMED', 'GETTING_STARTED_EMAIL', 'CHECK_IN_7DAY', 'SATISFACTION_SURVEY_30DAY', 'REVIEW_REQUEST', 'MAINTENANCE_REMINDER', 'DRIVER_BIOS_UPDATE_NOTICE', 'WARRANTY_REMINDER', 'UPGRADE_CAMPAIGN', 'TRADE_IN_OFFER', 'LOYALTY_CAMPAIGN', 'REFERRAL_INVITE', name='lifecycleeventtype'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'SENT', 'SKIPPED', 'FAILED', name='lifecycleeventstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('response_captured_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifecycle_events_order_id'), 'lifecycle_events', ['order_id'], unique=False)
    op.create_table('procurement_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procurement_product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'CONSUMED', 'RELEASED', name='procurementreservationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['procurement_product_id'], ['procurement_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_reservations_order_id'), 'procurement_reservations', ['order_id'], unique=False)
    op.create_index(op.f('ix_procurement_reservations_procurement_product_id'), 'procurement_reservations', ['procurement_product_id'], unique=False)
    op.create_table('quality_gate_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('evidence_photo_url', sa.String(), nullable=True),
    sa.Column('evidence_signature_ref', sa.String(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['quality_gate_checks.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'check_id', name='uq_qc_result_order_check')
    )
    op.create_index(op.f('ix_quality_gate_results_order_id'), 'quality_gate_results', ['order_id'], unique=False)
    op.create_table('usb_manifests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'BUILT', 'VALIDATED', 'WRITTEN_TO_MEDIA', 'FAILED', 'DIGITAL_FALLBACK', name='usbmanifeststatus'), nullable=False),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('capacity_bytes', sa.BigInteger(), nullable=True),
    sa.Column('file_manifest_json', sa.JSON(), nullable=True),
    sa.Column('built_at', sa.DateTime(), nullable=True),
    sa.Column('written_at', sa.DateTime(), nullable=True),
    sa.Column('written_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['usb_templates.id'], ),
    sa.ForeignKeyConstraint(['written_by'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('configurator_catalogue_visibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playbook_slot_id', sa.Integer(), nullable=False),
    sa.Column('catalogue_variant_id', sa.Integer(), nullable=False),
    sa.Column('is_publicly_visible', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catalogue_variant_id'], ['catalogue_variants.id'], ),
    sa.ForeignKeyConstraint(['playbook_slot_id'], ['playbook_slots.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configurator_catalogue_visibility_catalogue_variant_id'), 'configurator_catalogue_visibility', ['catalogue_variant_id'], unique=False)
    op.create_index(op.f('ix_configurator_catalogue_visibility_playbook_slot_id'), 'configurator_catalogue_visibility', ['playbook_slot_id'], unique=False)
    op.create_table('made_to_order_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('STANDARD', 'FAST_TRACK', name='queuepriority'), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('planning_started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # Deferred FKs on 'products' — target tables (builds, cx_documents, capture_3d_assets,
    # profit_calculations) are created after 'products' due to a circular reference
    # (products.profit_calculation_id <-> profit_calculations.product_id).
    op.create_foreign_key(None, 'products', 'builds', ['build_id'], ['id'])
    op.create_foreign_key(None, 'products', 'cx_documents', ['benchmark_report_document_id'], ['id'])
    op.create_foreign_key(None, 'products', 'capture_3d_assets', ['capture_3d_asset_id'], ['id'])
    op.create_foreign_key(None, 'products', 'profit_calculations', ['profit_calculation_id'], ['id'])
    op.add_column('order_photos', sa.Column('requirement_id', sa.Integer(), nullable=True))
    sa.Enum('ASSEMBLY', 'COMPLETION', 'PACKAGING', 'FINAL_BOXED', name='phototypeenum').create(op.get_bind(), checkfirst=True)
    op.add_column('order_photos', sa.Column('photo_type', sa.Enum('ASSEMBLY', 'COMPLETION', 'PACKAGING', 'FINAL_BOXED', name='phototypeenum'), nullable=True))
    op.add_column('order_photos', sa.Column('captured_by', sa.Integer(), nullable=True))
    op.add_column('order_photos', sa.Column('is_hero_shot', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_foreign_key(None, 'order_photos', 'customers', ['captured_by'], ['id'])
    op.create_foreign_key(None, 'order_photos', 'photo_requirements', ['requirement_id'], ['id'])
    op.add_column('orders', sa.Column('fast_track_selected', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('orders', sa.Column('fast_track_fee', sa.Float(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('packaging_playbook_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'packaging_playbooks', ['packaging_playbook_id'], ['id'])
    op.add_column('playbooks', sa.Column('emoji', sa.String(), nullable=True))
    op.add_column('playbooks', sa.Column('target_customer', sa.String(), nullable=True))
    op.add_column('playbooks', sa.Column('packaging_playbook_id', sa.Integer(), nullable=True))
    op.add_column('playbooks', sa.Column('activated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'playbooks', 'packaging_playbooks', ['packaging_playbook_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the deferred FKs on 'products' before their target tables are dropped below.
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'playbooks', type_='foreignkey')
    op.drop_column('playbooks', 'activated_at')
    op.drop_column('playbooks', 'packaging_playbook_id')
    op.drop_column('playbooks', 'target_customer')
    op.drop_column('playbooks', 'emoji')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'packaging_playbook_id')
    op.drop_column('orders', 'fast_track_fee')
    op.drop_column('orders', 'fast_track_selected')
    op.drop_constraint(None, 'order_photos', type_='foreignkey')
    op.drop_constraint(None, 'order_photos', type_='foreignkey')
    op.drop_column('order_photos', 'is_hero_shot')
    op.drop_column('order_photos', 'captured_by')
    op.drop_column('order_photos', 'photo_type')
    sa.Enum('ASSEMBLY', 'COMPLETION', 'PACKAGING', 'FINAL_BOXED', name='phototypeenum').drop(op.get_bind(), checkfirst=True)
    op.drop_column('order_photos', 'requirement_id')
    op.drop_table('made_to_order_queue')
    op.drop_index(op.f('ix_configurator_catalogue_visibility_playbook_slot_id'), table_name='configurator_catalogue_visibility')
    op.drop_index(op.f('ix_configurator_catalogue_visibility_catalogue_variant_id'), table_name='configurator_catalogue_visibility')
    op.drop_table('configurator_catalogue_visibility')
    op.drop_table('usb_manifests')
    op.drop_index(op.f('ix_quality_gate_results_order_id'), table_name='quality_gate_results')
    op.drop_table('quality_gate_results')
    op.drop_index(op.f('ix_procurement_reservations_procurement_product_id'), table_name='procurement_reservations')
    op.drop_index(op.f('ix_procurement_reservations_order_id'), table_name='procurement_reservations')
    op.drop_table('procurement_reservations')
    op.drop_index(op.f('ix_lifecycle_events_order_id'), table_name='lifecycle_events')
    op.drop_table('lifecycle_events')
    op.drop_index(op.f('ix_cx_documents_order_id'), table_name='cx_documents')
    op.drop_table('cx_documents')
    op.drop_table('cx_cost_records')
    op.drop_table('compatibility_rules')
    op.drop_table('capture_3d_assets')
    op.drop_table('builds')
    op.drop_table('usb_templates')
    op.drop_table('quality_gate_checks')
    op.drop_index(op.f('ix_procurement_purchases_procurement_product_id'), table_name='procurement_purchases')
    op.drop_table('procurement_purchases')
    op.drop_index(op.f('ix_procurement_product_suppliers_procurement_product_id'), table_name='procurement_product_suppliers')
    op.drop_table('procurement_product_suppliers')
    op.drop_table('photo_requirements')
    op.drop_index(op.f('ix_packaging_playbook_versions_packaging_playbook_id'), table_name='packaging_playbook_versions')
    op.drop_table('packaging_playbook_versions')
    op.drop_index(op.f('ix_packaging_playbook_components_packaging_playbook_id'), table_name='packaging_playbook_components')
    op.drop_table('packaging_playbook_components')
    op.drop_index(op.f('ix_channel_events_product_listing_id'), table_name='channel_events')
    op.drop_table('channel_events')
    op.drop_index(op.f('ix_product_listings_product_id'), table_name='product_listings')
    op.drop_table('product_listings')
    op.drop_index(op.f('ix_procurement_products_name'), table_name='procurement_products')
    op.drop_table('procurement_products')
    op.drop_index(op.f('ix_packaging_playbooks_slug'), table_name='packaging_playbooks')
    op.drop_index(op.f('ix_packaging_playbooks_name'), table_name='packaging_playbooks')
    op.drop_table('packaging_playbooks')
    op.drop_index(op.f('ix_profit_calculations_product_id'), table_name='profit_calculations')
    op.drop_index(op.f('ix_profit_calculations_order_id'), table_name='profit_calculations')
    op.drop_table('profit_calculations')
    op.drop_table('products')
    op.drop_index(op.f('ix_procurement_suppliers_name'), table_name='procurement_suppliers')
    op.drop_table('procurement_suppliers')
    op.drop_table('cx_document_templates')
    op.drop_table('bi_recommendations')
    # ### end Alembic commands ###
