"""
Gem Build model for speculative inventory recommendations.

A "gem" is a curated PC build recommendation generated by the LLM-powered
recommendation engine based on demand analysis and market conditions.
Gems represent ideal speculative inventory builds with strong profit margins
and confidence in demand.
"""
from sqlalchemy import Column, Integer, String, DateTime, Float, JSON, Enum as SQLEnum
from datetime import datetime
from app.database import Base
import enum
from typing import Optional


class GemRiskLevel(enum.Enum):
    """Risk assessment for gem build viability."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class GemBuild(Base):
    """
    Gem Build recommendation based on LLM analysis of demand and market conditions.

    Each gem represents a specific PC build configuration recommended for speculative
    inventory building based on:
    - Historical demand patterns (last 30 days)
    - Popular component combinations
    - Budget tier preferences
    - Market margin analysis
    """
    __tablename__ = "gem_builds"

    # Core identification
    id = Column(Integer, primary_key=True)
    name = Column(String(255), nullable=False, unique=True, index=True)  # e.g., "1440p Gaming Beast"
    use_case = Column(String(100), nullable=False, index=True)  # gaming, workstation, streaming, etc.
    target_budget_gbp = Column(Float, nullable=False)  # What this build is aimed at

    # Build specifications (stored as JSON for flexibility)
    specs = Column(JSON, nullable=False)  # Full component list: CPU, GPU, RAM, SSD, PSU, case, cooler, etc.

    # Financial analysis
    estimated_cost_to_build = Column(Float, nullable=False)  # What it costs us to build
    estimated_market_price = Column(Float, nullable=False)  # What we can sell it for
    margin_gbp = Column(Float, nullable=False)  # Profit in pounds
    margin_percent = Column(Float, nullable=False)  # Profit as percentage

    # Demand & Risk assessment
    confidence_score = Column(Integer, nullable=False)  # 0-100, how confident we are in demand
    risk_level = Column(SQLEnum(GemRiskLevel), nullable=False, default=GemRiskLevel.MEDIUM)
    recommended_quantity = Column(Integer, nullable=False, default=1)  # How many units to build

    # LLM-generated reasoning
    reasoning = Column(String(1000), nullable=False)  # Why the LLM recommended this

    # Cost breakdown details (for transparency)
    cost_breakdown = Column(JSON, nullable=False)  # {cpu: X, gpu: Y, ram: Z, ...}

    # Metadata
    analysis_period_days = Column(Integer, nullable=False, default=30)  # Based on last N days
    generated_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)

    def to_dict(self) -> dict:
        """Convert model to dictionary for JSON response."""
        return {
            "id": self.id,
            "name": self.name,
            "use_case": self.use_case,
            "target_budget": self.target_budget_gbp,
            "specs": self.specs,
            "estimated_cost": self.estimated_cost_to_build,
            "estimated_price": self.estimated_market_price,
            "margin_gbp": self.margin_gbp,
            "margin_percent": self.margin_percent,
            "confidence_score": self.confidence_score,
            "risk_level": self.risk_level.value if isinstance(self.risk_level, GemRiskLevel) else self.risk_level,
            "recommended_quantity": self.recommended_quantity,
            "reasoning": self.reasoning,
            "cost_breakdown": self.cost_breakdown,
            "analysis_period_days": self.analysis_period_days,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
