// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/add-build/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/add-build">> = Specific
  const handler = {} as typeof import("../../app/add-build/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/advertising-growth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/advertising-growth">> = Specific
  const handler = {} as typeof import("../../app/advertising-growth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/benchmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benchmarks">> = Specific
  const handler = {} as typeof import("../../app/benchmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/builds/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/builds/[id]">> = Specific
  const handler = {} as typeof import("../../app/builds/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/builds/[id]/sell/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/builds/[id]/sell">> = Specific
  const handler = {} as typeof import("../../app/builds/[id]/sell/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/builds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/builds">> = Specific
  const handler = {} as typeof import("../../app/builds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cases-3d-priority/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cases-3d-priority">> = Specific
  const handler = {} as typeof import("../../app/cases-3d-priority/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cases-3d-sourcing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cases-3d-sourcing">> = Specific
  const handler = {} as typeof import("../../app/cases-3d-sourcing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cases">> = Specific
  const handler = {} as typeof import("../../app/cases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/catalogue/cases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalogue/cases">> = Specific
  const handler = {} as typeof import("../../app/catalogue/cases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/catalogue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalogue">> = Specific
  const handler = {} as typeof import("../../app/catalogue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/catalogue/slots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalogue/slots">> = Specific
  const handler = {} as typeof import("../../app/catalogue/slots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/catalogue/variants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalogue/variants">> = Specific
  const handler = {} as typeof import("../../app/catalogue/variants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../app/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community">> = Specific
  const handler = {} as typeof import("../../app/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/components-3d-review/cases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/components-3d-review/cases">> = Specific
  const handler = {} as typeof import("../../app/components-3d-review/cases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/components-3d-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/components-3d-review">> = Specific
  const handler = {} as typeof import("../../app/components-3d-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/configurator-config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configurator-config">> = Specific
  const handler = {} as typeof import("../../app/configurator-config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cross-listing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cross-listing">> = Specific
  const handler = {} as typeof import("../../app/cross-listing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/demand/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demand">> = Specific
  const handler = {} as typeof import("../../app/demand/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev-listings/[channel]/[buildId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-listings/[channel]/[buildId]">> = Specific
  const handler = {} as typeof import("../../app/dev-listings/[channel]/[buildId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dispatch-zone/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dispatch-zone">> = Specific
  const handler = {} as typeof import("../../app/dispatch-zone/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ebay-preview-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ebay-preview-demo">> = Specific
  const handler = {} as typeof import("../../app/ebay-preview-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/email-events/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/email-events/[id]">> = Specific
  const handler = {} as typeof import("../../app/email-events/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/email-events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/email-events">> = Specific
  const handler = {} as typeof import("../../app/email-events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/flips/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flips/[id]">> = Specific
  const handler = {} as typeof import("../../app/flips/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/flips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flips">> = Specific
  const handler = {} as typeof import("../../app/flips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/intel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intel">> = Specific
  const handler = {} as typeof import("../../app/intel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/inventory/intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/intelligence">> = Specific
  const handler = {} as typeof import("../../app/inventory/intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../app/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/listing-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/listing-demo">> = Specific
  const handler = {} as typeof import("../../app/listing-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logs">> = Specific
  const handler = {} as typeof import("../../app/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/market-pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/market-pricing">> = Specific
  const handler = {} as typeof import("../../app/market-pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/metrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/metrics">> = Specific
  const handler = {} as typeof import("../../app/metrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/opportunities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opportunities">> = Specific
  const handler = {} as typeof import("../../app/opportunities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../app/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/parts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parts">> = Specific
  const handler = {} as typeof import("../../app/parts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pc-builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pc-builder">> = Specific
  const handler = {} as typeof import("../../app/pc-builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/performance">> = Specific
  const handler = {} as typeof import("../../app/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/playbooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playbooks">> = Specific
  const handler = {} as typeof import("../../app/playbooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/price-alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/price-alerts">> = Specific
  const handler = {} as typeof import("../../app/price-alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/problems/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/problems">> = Specific
  const handler = {} as typeof import("../../app/problems/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ram-watch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ram-watch">> = Specific
  const handler = {} as typeof import("../../app/ram-watch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule">> = Specific
  const handler = {} as typeof import("../../app/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/search-config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search-config">> = Specific
  const handler = {} as typeof import("../../app/search-config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/selling/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/selling">> = Specific
  const handler = {} as typeof import("../../app/selling/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sources">> = Specific
  const handler = {} as typeof import("../../app/sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sourcing/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sourcing/history">> = Specific
  const handler = {} as typeof import("../../app/sourcing/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sourcing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sourcing">> = Specific
  const handler = {} as typeof import("../../app/sourcing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/super-gems/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-gems">> = Specific
  const handler = {} as typeof import("../../app/super-gems/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assets-3d/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets-3d/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/assets-3d/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assets-3d/cases/[caseId]/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets-3d/cases/[caseId]/generate">> = Specific
  const handler = {} as typeof import("../../app/api/assets-3d/cases/[caseId]/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assets-3d/review-batches/[batchId]/assets/[assetId]/decision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets-3d/review-batches/[batchId]/assets/[assetId]/decision">> = Specific
  const handler = {} as typeof import("../../app/api/assets-3d/review-batches/[batchId]/assets/[assetId]/decision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assets-3d/review-batches/[batchId]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets-3d/review-batches/[batchId]/publish">> = Specific
  const handler = {} as typeof import("../../app/api/assets-3d/review-batches/[batchId]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assets-3d/review-batches/[batchId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets-3d/review-batches/[batchId]">> = Specific
  const handler = {} as typeof import("../../app/api/assets-3d/review-batches/[batchId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assets-3d/review-batches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets-3d/review-batches">> = Specific
  const handler = {} as typeof import("../../app/api/assets-3d/review-batches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assets-3d/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets-3d">> = Specific
  const handler = {} as typeof import("../../app/api/assets-3d/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/builds/[id]/preview-html/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/builds/[id]/preview-html">> = Specific
  const handler = {} as typeof import("../../app/api/builds/[id]/preview-html/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/builds/[id]/pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/builds/[id]/pricing">> = Specific
  const handler = {} as typeof import("../../app/api/builds/[id]/pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/builds/[id]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/builds/[id]/publish">> = Specific
  const handler = {} as typeof import("../../app/api/builds/[id]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/[caseId]/3d-reference-candidates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[caseId]/3d-reference-candidates">> = Specific
  const handler = {} as typeof import("../../app/api/cases/[caseId]/3d-reference-candidates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/[caseId]/3d-reference-candidates/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[caseId]/3d-reference-candidates/upload">> = Specific
  const handler = {} as typeof import("../../app/api/cases/[caseId]/3d-reference-candidates/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/[caseId]/3d-reference-image-search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[caseId]/3d-reference-image-search">> = Specific
  const handler = {} as typeof import("../../app/api/cases/[caseId]/3d-reference-image-search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/[caseId]/3d-reference-selection/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[caseId]/3d-reference-selection">> = Specific
  const handler = {} as typeof import("../../app/api/cases/[caseId]/3d-reference-selection/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/[caseId]/3d-sourcing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[caseId]/3d-sourcing">> = Specific
  const handler = {} as typeof import("../../app/api/cases/[caseId]/3d-sourcing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cases/priority-for-3d/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/priority-for-3d">> = Specific
  const handler = {} as typeof import("../../app/api/cases/priority-for-3d/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/listings/[listingId]/price-history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/listings/[listingId]/price-history">> = Specific
  const handler = {} as typeof import("../../app/api/listings/[listingId]/price-history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/nasa-bg/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nasa-bg">> = Specific
  const handler = {} as typeof import("../../app/api/nasa-bg/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/performance-card/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance-card/generate">> = Specific
  const handler = {} as typeof import("../../app/api/performance-card/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/performance-card/render/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/performance-card/render">> = Specific
  const handler = {} as typeof import("../../app/api/performance-card/render/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/proxy-glb/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy-glb">> = Specific
  const handler = {} as typeof import("../../app/api/proxy-glb/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/session/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session/login">> = Specific
  const handler = {} as typeof import("../../app/api/session/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/session/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session/logout">> = Specific
  const handler = {} as typeof import("../../app/api/session/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/proxy-api/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/proxy-api/[...path]">> = Specific
  const handler = {} as typeof import("../../app/proxy-api/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/components-3d-review/cases/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/components-3d-review/cases">> = Specific
  const handler = {} as typeof import("../../app/components-3d-review/cases/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
