// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/add-build" | "/advertising-growth" | "/benchmarks" | "/builds" | "/builds/[id]" | "/builds/[id]/sell" | "/cases" | "/cases-3d-priority" | "/cases-3d-sourcing" | "/catalogue" | "/catalogue/cases" | "/catalogue/slots" | "/catalogue/variants" | "/chat" | "/community" | "/components-3d-review" | "/components-3d-review/cases" | "/configurator-config" | "/cross-listing" | "/demand" | "/dev-listings/[channel]/[buildId]" | "/dispatch-zone" | "/ebay-preview-demo" | "/email-events" | "/email-events/[id]" | "/flips" | "/flips/[id]" | "/intel" | "/inventory" | "/inventory/intelligence" | "/listing-demo" | "/login" | "/logs" | "/market-pricing" | "/metrics" | "/opportunities" | "/orders" | "/orders/[id]" | "/parts" | "/pc-builder" | "/performance" | "/playbooks" | "/price-alerts" | "/problems" | "/ram-watch" | "/schedule" | "/search-config" | "/selling" | "/settings" | "/sources" | "/sourcing" | "/sourcing/history" | "/super-gems"
type AppRouteHandlerRoutes = "/api/assets-3d" | "/api/assets-3d/[id]" | "/api/assets-3d/cases/[caseId]/generate" | "/api/assets-3d/review-batches" | "/api/assets-3d/review-batches/[batchId]" | "/api/assets-3d/review-batches/[batchId]/assets/[assetId]/decision" | "/api/assets-3d/review-batches/[batchId]/publish" | "/api/builds/[id]/preview-html" | "/api/builds/[id]/pricing" | "/api/builds/[id]/publish" | "/api/cases/[caseId]/3d-reference-candidates" | "/api/cases/[caseId]/3d-reference-candidates/upload" | "/api/cases/[caseId]/3d-reference-image-search" | "/api/cases/[caseId]/3d-reference-selection" | "/api/cases/[caseId]/3d-sourcing" | "/api/cases/priority-for-3d" | "/api/listings/[listingId]/price-history" | "/api/nasa-bg" | "/api/performance-card/generate" | "/api/performance-card/render" | "/api/proxy-glb" | "/api/session/login" | "/api/session/logout" | "/proxy-api/[...path]"
type PageRoutes = never
type LayoutRoutes = "/" | "/components-3d-review/cases"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]" | "/api/gem-radar/[[...path]]" | "/health" | "/uploads/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/add-build": {}
  "/advertising-growth": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/api/assets-3d": {}
  "/api/assets-3d/[id]": { "id": string; }
  "/api/assets-3d/cases/[caseId]/generate": { "caseId": string; }
  "/api/assets-3d/review-batches": {}
  "/api/assets-3d/review-batches/[batchId]": { "batchId": string; }
  "/api/assets-3d/review-batches/[batchId]/assets/[assetId]/decision": { "batchId": string; "assetId": string; }
  "/api/assets-3d/review-batches/[batchId]/publish": { "batchId": string; }
  "/api/builds/[id]/preview-html": { "id": string; }
  "/api/builds/[id]/pricing": { "id": string; }
  "/api/builds/[id]/publish": { "id": string; }
  "/api/cases/[caseId]/3d-reference-candidates": { "caseId": string; }
  "/api/cases/[caseId]/3d-reference-candidates/upload": { "caseId": string; }
  "/api/cases/[caseId]/3d-reference-image-search": { "caseId": string; }
  "/api/cases/[caseId]/3d-reference-selection": { "caseId": string; }
  "/api/cases/[caseId]/3d-sourcing": { "caseId": string; }
  "/api/cases/priority-for-3d": {}
  "/api/gem-radar/[[...path]]": { "path"?: string[]; }
  "/api/listings/[listingId]/price-history": { "listingId": string; }
  "/api/nasa-bg": {}
  "/api/performance-card/generate": {}
  "/api/performance-card/render": {}
  "/api/proxy-glb": {}
  "/api/session/login": {}
  "/api/session/logout": {}
  "/benchmarks": {}
  "/builds": {}
  "/builds/[id]": { "id": string; }
  "/builds/[id]/sell": { "id": string; }
  "/cases": {}
  "/cases-3d-priority": {}
  "/cases-3d-sourcing": {}
  "/catalogue": {}
  "/catalogue/cases": {}
  "/catalogue/slots": {}
  "/catalogue/variants": {}
  "/chat": {}
  "/community": {}
  "/components-3d-review": {}
  "/components-3d-review/cases": {}
  "/configurator-config": {}
  "/cross-listing": {}
  "/demand": {}
  "/dev-listings/[channel]/[buildId]": { "channel": string; "buildId": string; }
  "/dispatch-zone": {}
  "/ebay-preview-demo": {}
  "/email-events": {}
  "/email-events/[id]": { "id": string; }
  "/flips": {}
  "/flips/[id]": { "id": string; }
  "/health": {}
  "/intel": {}
  "/inventory": {}
  "/inventory/intelligence": {}
  "/listing-demo": {}
  "/login": {}
  "/logs": {}
  "/market-pricing": {}
  "/metrics": {}
  "/opportunities": {}
  "/orders": {}
  "/orders/[id]": { "id": string; }
  "/parts": {}
  "/pc-builder": {}
  "/performance": {}
  "/playbooks": {}
  "/price-alerts": {}
  "/problems": {}
  "/proxy-api/[...path]": { "path": string[]; }
  "/ram-watch": {}
  "/schedule": {}
  "/search-config": {}
  "/selling": {}
  "/settings": {}
  "/sources": {}
  "/sourcing": {}
  "/sourcing/history": {}
  "/super-gems": {}
  "/uploads/[[...path]]": { "path"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/components-3d-review/cases": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
