"use client";

import { useEffect, useState } from "react";
import { TwinklingStars } from "./TwinklingStars";
import { PCCasesGallery } from "./PCCasesGallery";

interface PCCase {
  id: string;
  name: string;
  brand: string;
  model: string;
  formFactor: string;
  materials: string[];
  features: string[];
  status: "has-model" | "reference-only" | "pending";
  rating: number;
  reviews: number;
  price: number;
  originalPrice?: number;
  image?: string;
  threeDModelUrl?: string;
  referenceImages?: string[];
  youtubeLinks?: { url: string; timestamp?: string; title: string }[];
  specifications?: Record<string, string>;
}

const MOCK_CASES: PCCase[] = [
  {
    id: "1",
    name: "Corsair Obsidian 1000D Airflow",
    brand: "Corsair",
    model: "CC-9011211-WW",
    formFactor: "Full Tower",
    materials: ["Aluminum", "Tempered Glass"],
    features: ["RGB Lighting", "Motherboard Support: E-ATX", "Cooling: 8x 120mm fans"],
    status: "has-model",
    rating: 4.8,
    reviews: 324,
    price: 249.99,
    image: "https://via.placeholder.com/400x400?text=Corsair+Obsidian",
    threeDModelUrl: "https://sketchfab.com/models/embed",
    referenceImages: [
      "https://via.placeholder.com/800x600?text=Front",
      "https://via.placeholder.com/800x600?text=Side",
    ],
    youtubeLinks: [
      { url: "https://youtube.com", title: "Corsair Obsidian 1000D Review", timestamp: "0:45" },
      { url: "https://youtube.com", title: "Build Guide - Obsidian 1000D", timestamp: "2:30" },
    ],
    specifications: {
      "Dimensions": "598 x 566 x 244mm",
      "Weight": "17.5kg",
      "Volume": "83.2L",
      "Max GPU Length": "430mm",
      "Max CPU Cooler Height": "180mm",
    },
  },
  {
    id: "2",
    name: "NZXT H7 Flow RGB",
    brand: "NZXT",
    model: "CA-H7FW-RGB",
    formFactor: "Mid Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["RGB Lighting", "Airflow Focus", "Cable Management"],
    status: "has-model",
    rating: 4.6,
    reviews: 187,
    price: 149.99,
    image: "https://via.placeholder.com/400x400?text=NZXT+H7",
  },
  {
    id: "3",
    name: "Lian Li Lancool 216",
    brand: "Lian Li",
    model: "LANCOOL 216",
    formFactor: "Mid Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Tempered Glass", "Tool-free Design", "SSD Support"],
    status: "reference-only",
    rating: 4.5,
    reviews: 142,
    price: 89.99,
    image: "https://via.placeholder.com/400x400?text=Lian+Li",
  },
  {
    id: "4",
    name: "Fractal Design Torrent RGB",
    brand: "Fractal Design",
    model: "FD-C-TOR1-RGB",
    formFactor: "Full Tower",
    materials: ["Aluminum", "Tempered Glass"],
    features: ["Silent Operation", "RGB Fans", "Modular Design"],
    status: "has-model",
    rating: 4.9,
    reviews: 215,
    price: 289.99,
    originalPrice: 329.99,
    image: "https://via.placeholder.com/400x400?text=Fractal+Torrent",
  },
  {
    id: "5",
    name: "Be Quiet! Pure Base 500DX",
    brand: "Be Quiet!",
    model: "BQT-PB-500DX",
    formFactor: "Mid Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Silent Design", "Tool-free", "Cable Management"],
    status: "pending",
    rating: 4.4,
    reviews: 98,
    price: 119.99,
    image: "https://via.placeholder.com/400x400?text=Be+Quiet+Pure",
  },
  {
    id: "6",
    name: "Phanteks Eclipse P500A D-RGB",
    brand: "Phanteks",
    model: "PH-EC500ATG_DBK21",
    formFactor: "Mid Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Airflow Design", "D-RGB Fans", "SSD Support"],
    status: "has-model",
    rating: 4.7,
    reviews: 312,
    price: 159.99,
    image: "https://via.placeholder.com/400x400?text=Phanteks+Eclipse",
  },
  {
    id: "7",
    name: "Thermaltake Core P3",
    brand: "Thermaltake",
    model: "CA-1G4-00M1WN-00",
    formFactor: "Mini Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Open Frame", "Modular", "RGB Ready"],
    status: "reference-only",
    rating: 4.3,
    reviews: 76,
    price: 99.99,
    image: "https://via.placeholder.com/400x400?text=Thermaltake+Core",
  },
  {
    id: "8",
    name: "Deepcool Matrexx 55 V3.0",
    brand: "Deepcool",
    model: "R-MATREXX55V3",
    formFactor: "Mid Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Budget Friendly", "RGB Fans", "Airflow"],
    status: "has-model",
    rating: 4.2,
    reviews: 156,
    price: 69.99,
    image: "https://via.placeholder.com/400x400?text=Deepcool+Matrexx",
  },
  {
    id: "9",
    name: "Corsair 5000T RGB",
    brand: "Corsair",
    model: "CC-9011211-WW",
    formFactor: "Full Tower",
    materials: ["Aluminum", "Tempered Glass"],
    features: ["iCUE Compatible", "RGB Hub", "Power Button"],
    status: "has-model",
    rating: 4.8,
    reviews: 289,
    price: 399.99,
    originalPrice: 449.99,
    image: "https://via.placeholder.com/400x400?text=Corsair+5000T",
  },
  {
    id: "10",
    name: "MSI MPG GUNGNIR 110M",
    brand: "MSI",
    model: "MPG GUNGNIR 110M",
    formFactor: "Mini Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Compact", "Tool-free", "Integrated Fan"],
    status: "pending",
    rating: 4.5,
    reviews: 67,
    price: 129.99,
    image: "https://via.placeholder.com/400x400?text=MSI+GUNGNIR",
  },
  {
    id: "11",
    name: "Antec DF700 Flux",
    brand: "Antec",
    model: "DF700 FLUX",
    formFactor: "Mid Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Airflow", "RGB", "ATX Support"],
    status: "reference-only",
    rating: 4.4,
    reviews: 112,
    price: 109.99,
    image: "https://via.placeholder.com/400x400?text=Antec+DF700",
  },
  {
    id: "12",
    name: "Coolermaster HAF 500",
    brand: "Coolermaster",
    model: "RC-HA500-RGB",
    formFactor: "Full Tower",
    materials: ["Steel", "Mesh Front"],
    features: ["Airflow", "RGB Compatible", "Tool-free"],
    status: "has-model",
    rating: 4.6,
    reviews: 201,
    price: 149.99,
    image: "https://via.placeholder.com/400x400?text=Coolermaster+HAF",
  },
  {
    id: "13",
    name: "Louqe Ghost S1",
    brand: "Louqe",
    model: "Ghost S1 Mk3",
    formFactor: "SFF",
    materials: ["Aluminum", "Tempered Glass"],
    features: ["Ultra Compact", "Minimalist", "Tool-free"],
    status: "pending",
    rating: 4.7,
    reviews: 234,
    price: 199.99,
    image: "https://via.placeholder.com/400x400?text=Louqe+Ghost",
  },
  {
    id: "14",
    name: "Dan A4-SFX",
    brand: "Dan Cases",
    model: "A4-SFX v4.1",
    formFactor: "SFF",
    materials: ["Aluminum", "Tempered Glass"],
    features: ["Ultra Compact", "SFX PSU", "Modular"],
    status: "reference-only",
    rating: 4.8,
    reviews: 189,
    price: 229.99,
    image: "https://via.placeholder.com/400x400?text=Dan+A4",
  },
  {
    id: "15",
    name: "Streacom DA2",
    brand: "Streacom",
    model: "DA2",
    formFactor: "SFF",
    materials: ["Aluminum", "Mesh"],
    features: ["Fanless Design", "Passive Cooling", "Minimal"],
    status: "has-model",
    rating: 4.9,
    reviews: 145,
    price: 299.99,
    image: "https://via.placeholder.com/400x400?text=Streacom+DA2",
  },
  {
    id: "16",
    name: "Corsair Carbide Series 275Q",
    brand: "Corsair",
    model: "CC-9011131-WW",
    formFactor: "Mid Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Compact", "Cable Management", "Airflow"],
    status: "has-model",
    rating: 4.5,
    reviews: 176,
    price: 119.99,
    image: "https://via.placeholder.com/400x400?text=Corsair+275Q",
  },
  {
    id: "17",
    name: "ASUS Prime AP201",
    brand: "ASUS",
    model: "Prime AP201",
    formFactor: "Mini Tower",
    materials: ["Steel", "Mesh"],
    features: ["Budget Friendly", "Compact", "Cable Management"],
    status: "reference-only",
    rating: 4.1,
    reviews: 89,
    price: 59.99,
    image: "https://via.placeholder.com/400x400?text=ASUS+Prime",
  },
  {
    id: "18",
    name: "Hzxt Noctua Edition",
    brand: "HZXT",
    model: "NOCTUA-ED",
    formFactor: "Mid Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Noctua Integration", "Silent", "Premium Fans"],
    status: "pending",
    rating: 4.7,
    reviews: 123,
    price: 189.99,
    image: "https://via.placeholder.com/400x400?text=HZXT+Noctua",
  },
  {
    id: "19",
    name: "Sentey Gs7000x",
    brand: "Sentey",
    model: "GS-7000X",
    formFactor: "Full Tower",
    materials: ["Steel", "Mesh"],
    features: ["Gaming Design", "RGB Lighting", "ATX Support"],
    status: "has-model",
    rating: 4.3,
    reviews: 94,
    price: 139.99,
    image: "https://via.placeholder.com/400x400?text=Sentey+GS7000",
  },
  {
    id: "20",
    name: "Silverstone La Isla",
    brand: "Silverstone",
    model: "SST-LA01B",
    formFactor: "Mini ITX",
    materials: ["Aluminum", "Acrylic"],
    features: ["Unique Design", "Modular", "SFX PSU"],
    status: "reference-only",
    rating: 4.6,
    reviews: 107,
    price: 249.99,
    image: "https://via.placeholder.com/400x400?text=Silverstone+La",
  },
  {
    id: "21",
    name: "Jonsbo D40",
    brand: "Jonsbo",
    model: "D40",
    formFactor: "Mini Tower",
    materials: ["Aluminum", "Tempered Glass"],
    features: ["Compact", "Tool-free", "Aluminum Build"],
    status: "has-model",
    rating: 4.4,
    reviews: 78,
    price: 99.99,
    image: "https://via.placeholder.com/400x400?text=Jonsbo+D40",
  },
  {
    id: "22",
    name: "Caselabs Merlin S",
    brand: "Caselabs",
    model: "Merlin S",
    formFactor: "Mid Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Extreme Customization", "Watercooling Ready", "Premium"],
    status: "pending",
    rating: 4.9,
    reviews: 156,
    price: 379.99,
    image: "https://via.placeholder.com/400x400?text=Caselabs+Merlin",
  },
  {
    id: "23",
    name: "Thermaltake Suppressor F51",
    brand: "Thermaltake",
    model: "CA-1I7-00M1WN-00",
    formFactor: "Mid Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Silent Design", "Airflow", "Noise Reduction"],
    status: "has-model",
    rating: 4.5,
    reviews: 134,
    price: 149.99,
    image: "https://via.placeholder.com/400x400?text=Thermaltake+F51",
  },
  {
    id: "24",
    name: "Raijintek Styx",
    brand: "Raijintek",
    model: "STYX",
    formFactor: "Mini ITX",
    materials: ["Aluminum", "Tempered Glass"],
    features: ["Ultra Compact", "Tool-free", "SFX PSU"],
    status: "reference-only",
    rating: 4.7,
    reviews: 98,
    price: 179.99,
    image: "https://via.placeholder.com/400x400?text=Raijintek+Styx",
  },
  {
    id: "25",
    name: "Evolv X",
    brand: "Phanteks",
    model: "PH-ES518XTC_DBK01",
    formFactor: "Full Tower",
    materials: ["Aluminum", "Tempered Glass"],
    features: ["Premium Build", "Modular", "RGB Integration"],
    status: "has-model",
    rating: 4.8,
    reviews: 267,
    price: 279.99,
    image: "https://via.placeholder.com/400x400?text=Phanteks+Evolv",
  },
  {
    id: "26",
    name: "Fractal Meshify C",
    brand: "Fractal Design",
    model: "FD-CA-MESH-C",
    formFactor: "Mid Tower",
    materials: ["Steel", "Mesh Front"],
    features: ["Airflow Optimized", "Clean Design", "Cable Management"],
    status: "pending",
    rating: 4.6,
    reviews: 241,
    price: 99.99,
    image: "https://via.placeholder.com/400x400?text=Fractal+Meshify",
  },
  {
    id: "27",
    name: "Lian Li Lancool 215",
    brand: "Lian Li",
    model: "Lancool 215",
    formFactor: "Mid Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Affordable", "Airflow", "RGB Compatible"],
    status: "has-model",
    rating: 4.3,
    reviews: 189,
    price: 79.99,
    image: "https://via.placeholder.com/400x400?text=Lian+Li+215",
  },
  {
    id: "28",
    name: "Beautystar BS-01",
    brand: "Beautystar",
    model: "BS-01",
    formFactor: "Mini Tower",
    materials: ["Aluminum", "Acrylic"],
    features: ["Unique Design", "Tool-free", "Compact"],
    status: "reference-only",
    rating: 4.2,
    reviews: 45,
    price: 89.99,
    image: "https://via.placeholder.com/400x400?text=Beautystar+BS",
  },
  {
    id: "29",
    name: "Kyoto Kagura",
    brand: "Kyoto",
    model: "Kagura",
    formFactor: "Mini Tower",
    materials: ["Aluminum", "Tempered Glass"],
    features: ["Minimalist", "Japanese Design", "Premium Build"],
    status: "has-model",
    rating: 4.9,
    reviews: 112,
    price: 199.99,
    image: "https://via.placeholder.com/400x400?text=Kyoto+Kagura",
  },
  {
    id: "30",
    name: "In-Win A1 Plus",
    brand: "In-Win",
    model: "A1 Plus",
    formFactor: "Mini Tower",
    materials: ["Aluminum", "Tempered Glass"],
    features: ["Modular PSU", "Compact", "Tool-free Design"],
    status: "pending",
    rating: 4.5,
    reviews: 87,
    price: 159.99,
    image: "https://via.placeholder.com/400x400?text=In-Win+A1",
  },
  {
    id: "31",
    name: "Newegg ABS Stratos",
    brand: "Newegg",
    model: "ABS-STRATOS",
    formFactor: "Mid Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Pre-built Ready", "RGB System", "Budget Gaming"],
    status: "has-model",
    rating: 4.1,
    reviews: 76,
    price: 89.99,
    image: "https://via.placeholder.com/400x400?text=Newegg+Stratos",
  },
  {
    id: "32",
    name: "Vetroo V5",
    brand: "Vetroo",
    model: "V5",
    formFactor: "Mini Tower",
    materials: ["Steel", "Tempered Glass"],
    features: ["Budget Friendly", "RGB Fans", "Dual-Chamber"],
    status: "reference-only",
    rating: 4.4,
    reviews: 203,
    price: 69.99,
    image: "https://via.placeholder.com/400x400?text=Vetroo+V5",
  },
];

export default function Components3DReviewPage() {
  const [cases, setCases] = useState<PCCase[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulate loading from API
    const timer = setTimeout(() => {
      setCases(MOCK_CASES);
      setLoading(false);
    }, 500);

    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="relative min-h-screen bg-slate-950">
      {/* Starfield Background */}
      <TwinklingStars />

      {/* Content */}
      <div className="relative z-10">
        <div className="max-w-7xl mx-auto px-6 py-12">
          <PCCasesGallery cases={cases} loading={loading} />
        </div>
      </div>
    </div>
  );
}
