var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/cases-3d-priority/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-iofim._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1w0b637._.js")
R.c("server/chunks/ssr/[root-of-the-server]__174cgu_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e7ih-s._.js")
R.c("server/chunks/ssr/_0nolu81._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_cases-3d-priority_page_actions_1fsey50.js")
R.m(84848)
module.exports=R.m(84848).exports
