import { NextResponse } from 'next/server';

export async function GET(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const backendOrigin = (process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4311').replace(/\/$/, '');
    const apiUrl = `${backendOrigin}/api/manual-builds/${id}`;
    const res = await fetch(apiUrl, {
      signal: AbortSignal.timeout(10000),
    });

    if (!res.ok) {
      const errorData = await res.text();
      console.error(`API error fetching ${apiUrl}:`, res.status, errorData);
      return NextResponse.json(
        { error: 'Build not found', detail: errorData, status: res.status },
        { status: res.status }
      );
    }

    const build = await res.json();

    if (!build.generated_title || !build.generated_description) {
      return NextResponse.json(
        { error: 'Build missing generated content' },
        { status: 404 }
      );
    }

    const escapeHtml = (text: string) =>
      text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');

    const formatDescription = (desc: string) => {
      return desc
        .split('\n\n')
        .map((para) => `<p>${escapeHtml(para).replace(/\n/g, '<br>')}</p>`)
        .join('');
    };

    const htmlContent = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(build.generated_title)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #f5f5f5; padding: 20px; }
    .container { max-width: 900px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 32px 24px; text-align: center; }
    .header h1 { font-size: 32px; font-weight: 700; line-height: 1.2; }
    .content { padding: 40px; }
    .hero-image { width: 100%; height: auto; border-radius: 8px; margin-bottom: 32px; display: block; }
    .description { font-size: 15px; line-height: 1.8; color: #333; }
    .description p { margin-bottom: 16px; }
    .description p:last-child { margin-bottom: 0; }
    .footer { background: #f9f9f9; padding: 16px 40px; border-top: 1px solid #eee; font-size: 12px; color: #666; text-align: center; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>${escapeHtml(build.generated_title)}</h1>
    </div>
    <div class="content">
      ${build.hero_photo_url ? `<img src="${escapeHtml(build.hero_photo_url)}" alt="Product preview" class="hero-image">` : ''}
      <div class="description">
        ${formatDescription(build.generated_description)}
      </div>
    </div>
    <div class="footer">
      <p>Preview generated by FlipFlop • Windows 11 Pro Activated</p>
    </div>
  </div>
</body>
</html>`;

    return new NextResponse(htmlContent, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
      },
    });
  } catch (error) {
    console.error('Preview HTML error:', error);
    return NextResponse.json(
      { error: 'Failed to generate preview' },
      { status: 500 }
    );
  }
}
